name: Run Gradle on Push
on:
  push:
    branches:
      - master
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: publishMavenJavaPublicationToGithubRepository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}